package com.rits.orm.drivers
import com.rits.jdbc.Jdbc
import com.rits.orm.TypeRegistry
import com.rits.orm.ColumnBase
import com.rits.jdbc.UpdateResultWithGeneratedKeys

/**
 * @author kostantinos.kougios
 *
 * 2 Sep 2011
 */
class Mysql(override val jdbc: Jdbc, override val typeRegistry: TypeRegistry) extends Driver {

	protected[orm] override def getAutoGenerated(ur: UpdateResultWithGeneratedKeys, column: ColumnBase): Any = ur.keys.get("GENERATED_KEY").get
}