package com.googlecode.mapperdao

case class PK(columnName: String, isAutoGenerated: Boolean, sequence: Option[String]) extends SimpleColumn {
	def alias = columnName
	def isSequence = sequence.isDefined
}
