package com.googlecode.mapperdao

case class PK(name: String, isAutoGenerated: Boolean, sequence: Option[String], val tpe: Class[_]) extends SimpleColumn {
	def alias = name
	def isSequence = sequence.isDefined
}
