package com.googlecode.mapperdao

case class PK(column: SimpleColumn) extends SimpleColumn {
	def columnName = column.columnName
	def alias = columnName
	def isAutoGenerated = column.isAutoGenerated
	def isSequence = column.isSequence
}
