package com.googlecode.mapperdao.ops

import com.googlecode.mapperdao._
import java.util.IdentityHashMap

/**
 * entities are converted to PersistOps
 *
 * @author kostantinos.kougios
 *
 * 21 Nov 2012
 */
class PersistOperations {

	private val alreadyProcessed = new IdentityHashMap[Any, List[PersistOp[_, _, _]]]

	def toInsertOps[ID, PC <: DeclaredIds[ID], T](
		entity: Entity[ID, PC, T],
		o: T,
		valuesMap: ValuesMap): List[PersistOp[ID, PC, T]] = {
		Nil
	}

	private def insert[ID, PC <: DeclaredIds[ID], T](
		entity: Entity[ID, PC, T],
		o: T,
		valuesMap: ValuesMap,
		currentPriority: Int): List[PersistOp[ID, PC, T]] = {
		val op = alreadyProcessed.get(o)
		if (op == null) {
			val tpe = entity.tpe
			val table = tpe.table
			val columnAndValues = table.toListOfColumnAndValueTuples(table.simpleTypeNotAutoGeneratedColumns, o)
			val ops = InsertOp(entity, o, currentPriority, columnAndValues) :: Nil
			alreadyProcessed.put(o, ops)
			ops
		} else op.asInstanceOf[List[PersistOp[ID, PC, T]]]
	}
}