package com.googlecode.mapperdao
import com.googlecode.mapperdao.jdbc.Setup
import org.junit.runner.RunWith
import org.scalatest.matchers.ShouldMatchers
import org.scalatest.FunSuite
import org.scalatest.junit.JUnitRunner

/**
 * @author kostantinos.kougios
 *
 * Jan 18, 2012
 */
@RunWith(classOf[JUnitRunner])
class ManyToManyUseExternalLoaderSuite extends FunSuite with ShouldMatchers {
	var counter = 0

	val (jdbc, mapperDao, queryDao) = Setup.setupMapperDao(TypeRegistry(ProductEntity, AttributeEntity))

	if (Setup.database == "h2") {
		test("persists/select externally") {
			createTables

			val product = Product("p1", Set(Attribute(1, "a1"), Attribute(2, "a2")))
			val inserted = mapperDao.insert(ProductEntity, product)
			inserted should be === product
			mapperDao.select(ProductEntity, inserted.id).get should be === inserted
		}
	}
	def createTables {
		counter = 0
		Setup.dropAllTables(jdbc)
		Setup.queries(this, jdbc).update("ddl")
	}

	case class Product(val name: String, val attributes: Set[Attribute])
	case class Attribute(val id: Int, val name: String)

	object ProductEntity extends Entity[IntId, Product](classOf[Product]) {
		val id = key("id") autogenerated (_.id)
		val name = column("name") to (_.name)
		val attributes = manytomany(AttributeEntity) to (_.attributes)

		def constructor(implicit m) = new Product(name, attributes) with IntId with Persisted {
			val id: Int = ProductEntity.id
		}
	}

	object AttributeEntity extends ExternalEntity[Attribute](classOf[Attribute]) {

		def primaryKeyValues(a) = List(a.id)

		def select(selectConfig) = {
			counter += 1
			new Attribute(counter, "x" + counter)
		}
	}

}