package com.googlecode.mapperdao
import com.googlecode.mapperdao.jdbc.Setup
import org.scalatest.junit.JUnitRunner
import org.scalatest.FunSuite
import org.scalatest.matchers.ShouldMatchers
import org.junit.runner.RunWith
/**
 * @author kostantinos.kougios
 *
 * 16 Dec 2011
 */
@RunWith(classOf[JUnitRunner])
class QueryAutogeneratedSuite extends FunSuite with ShouldMatchers {

	val typeRegistry = TypeRegistry(ComputerEntity)
	val (jdbc, mapperDao, queryDao) = Setup.setupMapperDao(typeRegistry)

	// an alias
	val je = ComputerEntity

	import Query._

	test("query returns id") {
		createTables
		val inserted = mapperDao.insert(ComputerEntity, Computer("job1", None))
		val l = queryDao.query(select from je)
		l.head.id should be === 1
	}

	def createTables {
		Setup.dropAllTables(jdbc)
		Setup.database match {
			case "oracle" => Setup.createMySeq(jdbc)
			case _ =>
		}
		Setup.queries(this, jdbc).update("ddl")
	}

	case class Company(name: String)
	case class Computer(name: String, company: Option[Company])

	object CompanyEntity extends Entity[IntId, Company](classOf[Company]) {
		val id = key("id") autogenerated (_.id)
		val name = column("name") to (_.name)

		def constructor(implicit m) = new Company(name) with IntId with Persisted {
			val id: Int = id
		}
	}
	object ComputerEntity extends Entity[IntId, Computer](classOf[Computer]) {
		val id = key("id") autogenerated (_.id)
		val name = column("name") to (_.name)
		val company = manytoone(CompanyEntity) option (_.company)

		def constructor(implicit m) = new Computer(name, company) with IntId with Persisted {
			val id: Int = id
		}
	}
}