package com.googlecode.mapperdao

import com.googlecode.mapperdao.jdbc.Setup
import org.scalatest.FunSuite
import org.scalatest.matchers.ShouldMatchers
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner
import com.googlecode.mapperdao.schema.SchemaModifications

/**
 * @author kkougios
 */
@RunWith(classOf[JUnitRunner])
class SchemaModificationsSuite extends FunSuite with ShouldMatchers
{
	val (jdbc, mapperDao, queryDao) = Setup.setupMapperDao(TypeRegistry(PersonEntity))

	if (Setup.database == "h2") {

		val modifications = SchemaModifications(
			name => "tmp_" + name
		)
		val uc = UpdateConfig.default.copy(schemaModifications = modifications)
		val sc = SelectConfig.default.copy(schemaModifications = modifications)
		val dc = DeleteConfig.default.copy(schemaModifications = modifications)
		val qc = QueryConfig.default.copy(schemaModifications = modifications)

		test("table name modified CRUD") {
			createTables()

			val List(i1, _) = mapperDao.insertBatch(uc, PersonEntity, List(Person("p1"), Person("p2")))

			val s1 = mapperDao.select(sc, PersonEntity, i1.id).get
			s1 should be(i1)

			val u1 = mapperDao.update(uc, PersonEntity, s1, Person("p1updated"))

			val s1u = mapperDao.select(sc, PersonEntity, i1.id).get
			s1u should be(u1)

			mapperDao.delete(dc, PersonEntity, s1u)

			mapperDao.select(sc, PersonEntity, i1.id) should be(None)
		}

		test("table name modified Query") {
			createTables()

			val List(i1, i2) = mapperDao.insertBatch(uc, PersonEntity, List(Person("p1"), Person("p2")))

			import Query._
			val r = queryDao.query(qc, select from PersonEntity).toSet

			r should be(Set(i1, i2))
		}

		def createTables() {
			Setup.dropAllTables(jdbc)
			Setup.queries(this, jdbc).update("person")
		}
	}

	case class Person(name: String)

	object PersonEntity extends Entity[Int, SurrogateIntId, Person]
	{
		val id = key("id") autogenerated (_.id)
		val name = column("name") to (_.name)

		def constructor(implicit m: ValuesMap) = new Person(name) with Stored
		{
			val id: Int = PersonEntity.id
		}
	}

}
