package com.googlecode.mapperdao.jdbc

import com.googlecode.mapperdao._
import com.googlecode.mapperdao.ops._
import com.googlecode.mapperdao.drivers.Driver
import org.springframework.jdbc.core.SqlParameterValue

/**
 * converts commands to database operations, executes
 * them and returns the resulting entity
 *
 * @author kostantinos.kougios
 *
 * 22 Nov 2012
 */
class CmdToDatabase(driver: Driver) {
	private val jdbc = driver.jdbc

	def insert[ID, PC <: DeclaredIds[ID], T](
		cmds: List[PersistCmd[ID, PC, T]]): List[T with PC] = {
		val sqlCmds = cmds.map { cmd =>
			val sql = toSql(cmd)
			(sql.sql, cmd, sql.values.toArray)
		}

		val batchResults = sqlCmds.groupBy(_._1).map {
			case (sql, cmds) =>
				val entity = cmds.head._2.entity
				val table = entity.tpe.table
				val autoGeneratedColumnNames = table.autoGeneratedColumnNamesArray
				val bo = BatchOptions(driver.batchStrategy, autoGeneratedColumnNames)
				val args = cmds.map {
					case (_, _, values) =>
						values
				}.toArray
				jdbc.batchUpdate(bo, sql, args)
		}

		Nil
	}

	private def toSql(cmd: PersistCmd[_, _, _]) = cmd match {
		case InsertCmd(entity, o, columns) =>
			driver.insertSql(entity.tpe, columns).result
	}
}